# fly.toml app configuration file generated for ghosty-morning-water-1180 on 2025-01-22T21:03:02+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ghosty-morning-water-1180'
primary_region = 'sin'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  DB_CONNECTION='sqlite'
  DB_DATABASE='/var/www/html/ghosty_db/database.sqlite'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "sqlite_ghost_db"
  destination ="/var/www/html/ghosty_db"
